name: composer
description: "Executes composer command inside of php container. Example: `make composer require drupal/devel`."
command: |
  cd $project_root
  so mi "Running composer $command ..."
  docker compose exec php sh -c "composer $command"
